import { escapeHtml, icon, sectionHeader, statusPill } from "../components/ui.js";
import { activeEvent, currentScout, getMatchTeams, matchLabel } from "../utils/domain.js";

export function renderAdmin({ state }) {
  const event = activeEvent(state);
  const scout = currentScout(state);
  const teams = state.teams || [];
  const scouts = state.scouts || [];
  const records = (state.scoutingRecords || []).filter((record) => String(record.eventId) === String(event?.id));
  const matches = (state.matches || []).filter((match) => String(match.eventId) === String(event?.id));
  return `<section class="page">
    ${sectionHeader({ eyebrow: "ORGANIZAÇÃO", title: "Gerenciar evento", description: "Prepare os cadastros e a agenda. Tudo pronto para a próxima partida.", action: `<button class="button primary" data-action="open-setup">${icon("plus",17)} Preparação guiada</button>` })}
    ${!event || !scout ? `<div class="notice">${icon("clipboard",20)}<span>Começando agora? A preparação guiada reúne evento, scout, equipes e primeira partida em três passos.</span></div>` : ""}
    <div class="admin-grid">
      <section class="card pad"><div class="card-header"><div><h2>Seus eventos</h2><span class="subtle">Selecione qual evento você quer acompanhar.</span></div>${icon("matches",20)}</div><div class="admin-list">${state.events.map((item) => `<div class="admin-list__item"><div><strong>${escapeHtml(item.name)}</strong><span>${escapeHtml(item.type || "Evento")}</span></div>${String(item.id) === String(event?.id) ? '<span class="status-pill good">Ativo</span>' : `<button class="button small" data-action="set-active-event" data-event-id="${escapeHtml(item.id)}">Ativar</button>`}</div>`).join("") || '<p class="subtle">Você ainda não criou um evento.</p>'}</div><details class="admin-create"><summary>${icon("plus",16)} Criar outro evento</summary><form data-form="add-event"><div class="field"><label for="event-name">Nome do evento</label><input id="event-name" name="name" placeholder="Ex.: Regional Sul" required maxlength="70" /></div><div class="field"><label for="event-type">Tipo</label><select id="event-type" name="type"><option>Regional</option><option value="Practice">Treino</option><option value="Qualifier">Classificatória</option><option value="Championship">Campeonato</option></select></div><div class="form-actions"><button class="button primary" type="submit">Criar e ativar</button></div></form></details></section>
      <section class="card pad"><div class="card-header"><div><h2>Equipes</h2><span class="subtle">${teams.length} equipes cadastradas.</span></div>${icon("teams",20)}</div><div class="admin-list">${teams.slice(0,8).map((team) => `<div class="admin-list__item"><div><strong>${escapeHtml(team.number)} · ${escapeHtml(team.name)}</strong><span>${escapeHtml(team.city || "Equipe FTC")}</span></div><button class="button small" data-action="open-team" data-team-id="${escapeHtml(team.id)}">Perfil</button></div>`).join("") || '<p class="subtle">Adicione as equipes que vão participar das partidas.</p>'}</div><div class="form-actions"><button class="button" data-action="open-add-team">${icon("plus",16)} Adicionar equipe</button><button class="button ghost" data-action="open-bulk-teams">Colar lista</button></div></section>
      <section class="card pad"><div class="card-header"><div><h2>Quem está observando</h2><span class="subtle">Escolha seu perfil de scout neste dispositivo.</span></div>${icon("user",20)}</div><div class="admin-list">${scouts.map((person) => `<div class="admin-list__item"><div><strong>${escapeHtml(person.name)}</strong><span>${escapeHtml(person.role || "Scout")}</span></div>${String(person.id) === String(scout?.id) ? '<span class="status-pill good">Você</span>' : `<button class="button small" data-action="set-current-scout" data-scout-id="${escapeHtml(person.id)}">Usar perfil</button>`}</div>`).join("") || '<p class="subtle">O scout identifica quem salvou cada observação.</p>'}</div><details class="admin-create"><summary>${icon("plus",16)} Adicionar scout</summary><form data-form="add-scout"><div class="field"><label for="new-scout-name">Nome</label><input id="new-scout-name" name="name" placeholder="Nome do scout" required maxlength="60" /></div><div class="field"><label for="new-scout-role">Função</label><select id="new-scout-role" name="role"><option>Scout</option><option>Estratégia</option><option>Administrador</option></select></div><div class="form-actions"><button class="button" type="submit">Adicionar scout</button></div></form></details></section>
      <section class="card pad" style="grid-column:1/-1"><div class="card-header"><div><h2>Agenda de ${escapeHtml(event?.name || "partidas")}</h2><span class="subtle">Duas equipes por aliança, quatro observações por partida.</span></div><button class="button small" data-action="open-add-match">${icon("plus",16)} Nova partida</button></div><div class="admin-list">${matches.map((match) => `<div class="admin-list__item"><div><strong>${escapeHtml(matchLabel(match))}</strong><span>${getMatchTeams(state,match).map((entry) => escapeHtml(entry.team?.number || "—")).join(" · ")}</span></div>${statusPill(match.status === "complete" ? "Completa" : match.status === "in_progress" ? "Em andamento" : "Não iniciada")}</div>`).join("") || '<p class="subtle">Crie a primeira partida para liberar as observações.</p>'}</div></section>
      <section class="card pad" style="grid-column:1/-1"><div class="card-header"><div><h2>Observações salvas</h2><span class="subtle">Consulte os registros e corrija o que for necessário.</span></div>${icon("clipboard",20)}</div><div class="admin-list">${records.slice().sort((a,b) => new Date(b.savedAt || 0) - new Date(a.savedAt || 0)).map((record) => { const team = teams.find((item) => String(item.id) === String(record.teamId)); const match = matches.find((item) => String(item.id) === String(record.matchId)); return `<div class="admin-list__item"><div><strong>${escapeHtml(team?.number || "—")} · ${escapeHtml(team?.name || "Equipe")}</strong><span>${escapeHtml(matchLabel(match))}</span></div><div class="record-actions"><button class="button small" data-action="open-record" data-record-id="${escapeHtml(record.id)}">Consultar</button><button class="icon-button" data-action="request-delete-record" data-record-id="${escapeHtml(record.id)}" aria-label="Excluir observação da equipe ${escapeHtml(team?.number)}">${icon("close",16)}</button></div></div>`; }).join("") || '<p class="subtle">As observações concluídas aparecerão aqui.</p>'}</div></section>
    </div>
  </section>`;
}

export function renderDeleteRecordConfirm(recordId) {
  return `<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="delete-record-title" tabindex="-1"><header class="modal__header"><div><span class="eyebrow">Excluir observação</span><h2 id="delete-record-title">Remover este registro?</h2><p>O scouting será removido e as estatísticas do evento serão atualizadas.</p></div><button class="icon-button" data-action="close-modal" aria-label="Fechar">${icon("close")}</button></header><div class="modal__body"><div class="notice warning">${icon("alert",18)} Esta exclusão não pode ser desfeita.</div></div><footer class="modal__footer"><button class="button" data-action="close-modal">Cancelar</button><button class="button danger" data-action="confirm-delete-record" data-record-id="${escapeHtml(recordId)}">Excluir observação</button></footer></section></div>`;
}
