import { getRanking } from "../services/analytics.js";
import { escapeHtml, icon, number, progressBar, sectionHeader } from "../components/ui.js";
import { RATING_WEIGHT_LABELS } from "../types/domain.js";

export function renderRanking({ state }) {
  const ranking = getRanking(state);
  const weights = state.settings?.ratingWeights || {};
  const podium = ranking.slice(0,3);
  return `<section class="page">
    ${sectionHeader({ eyebrow: "Ranking interno", title: "Scouting Rating", description: "Índice configurável baseado apenas nos dados coletados; não substitui o ranking oficial da FTC.", action: `<button class="button" data-view="season">${icon("settings",16)} Ajustar pesos</button>` })}
    ${podium.length ? `<div class="ranking-podium">${podium.map((profile,index) => `<button class="podium-card" data-action="open-team" data-team-id="${escapeHtml(profile.teamId || profile.id)}"><span class="podium-medal">${index + 1}</span><strong>${escapeHtml(profile.teamNumber || "—")}</strong><span>${escapeHtml(profile.name || "Equipe")}</span><b>${number(profile.scoutingRating,1)}</b></button>`).join("")}</div>` : ""}
    <div class="grid" style="grid-template-columns:minmax(0,1fr);gap:16px"><section class="card pad"><div class="card-header"><div><h2>Classificação completa</h2><span class="subtle">Atualiza automaticamente depois de cada scouting salvo.</span></div></div><div class="team-list">${ranking.map((profile) => `<button class="team-row" data-action="open-team" data-team-id="${escapeHtml(profile.teamId || profile.id)}"><span class="team-label"><b>#${profile.rank} · ${escapeHtml(profile.teamNumber || "—")}</b><span>${escapeHtml(profile.name || "Equipe")} · média ${number(profile.averageScore,1)} · ${profile.matchesAnalyzed} scouts</span></span><span class="average">${number(profile.consistency)}% const.</span><span class="rating">${number(profile.scoutingRating,1)}</span><span>${icon("chevron",16)}</span></button>`).join("") || '<div class="empty-state"><h3>Sem ranking</h3><p>O ranking começa a aparecer quando houver registros salvos.</p></div>'}</div></section><section class="card pad"><div class="card-header"><div><h2>Como o Rating é calculado</h2><span class="subtle">Pesos atuais da temporada.</span></div></div><div class="rating-breakdown">${Object.entries(RATING_WEIGHT_LABELS).map(([key,label]) => { const value=Number(weights[key]||0); return `<div class="rating-breakdown__row"><label>${escapeHtml(label)}</label>${progressBar(Math.abs(value),{max:50,tone:value<0?"red":"cyan"})}<output style="color:${value<0?"var(--red)":"var(--cyan)"}">${value>0?"+":""}${value}</output></div>`; }).join("")}</div><div class="card inset pad" style="margin-top:15px"><span class="icon-text">${icon("alert",16)} Falhas e penalidades reduzem a nota quando seus pesos são negativos.</span></div></section></div>
  </section>`;
}
