import { escapeHtml, icon, sectionHeader } from "../components/ui.js";
import { activeSeason } from "../utils/domain.js";
import { RATING_WEIGHT_LABELS } from "../types/domain.js";

const phaseInfo = {
  auto: ["Autonomous", "Antes do controle manual"],
  teleop: ["TeleOp", "Controle manual e ciclos"],
  endgame: ["Endgame", "Ações finais da partida"],
};

function actionEditor(action) {
  return `<article class="config-action" data-action-row="${escapeHtml(action.id)}"><div><input class="inline-label" data-action="change-season-action-label" data-action-id="${escapeHtml(action.id)}" value="${escapeHtml(action.label)}" aria-label="Nome da ação" /><p>${escapeHtml(action.inputType || "counter")} · limite ${action.max ?? "—"}${action.countsTowardCycles ? " · conta ciclos" : ""}</p></div><input type="number" min="0" max="999" data-action="change-season-action-points" data-action-id="${escapeHtml(action.id)}" value="${Number(action.points) || 0}" aria-label="Pontos para ${escapeHtml(action.label)}" /><button data-action="request-delete-season-action" data-action-id="${escapeHtml(action.id)}" title="Remover ação" aria-label="Remover ${escapeHtml(action.label)}">${icon("close", 16)}</button></article>`;
}

export function renderSeason({ state }) {
  const season = activeSeason(state) || { id: "season", name: "Temporada", gameName: "Jogo", actions: { auto: [], teleop: [], endgame: [] } };
  const weights = state.settings?.ratingWeights || {};
  return `<section class="page">
    ${sectionHeader({ eyebrow: "Administração", title: "Configuração da Temporada", description: "A tela de scouting é gerada a partir destas ações; alterações futuras não exigem reprogramação." })}
    <div class="grid" style="grid-template-columns:minmax(0,1fr)">
      <section class="card pad"><div class="card-header"><div><h2>Identidade da temporada</h2><span class="subtle">Configuração ativa do evento.</span></div></div><form data-form="season-identity"><div class="form-row two"><div class="field"><label for="season-name">Nome da temporada</label><input id="season-name" name="name" value="${escapeHtml(season.name || "")}" required /></div><div class="field"><label for="season-game">Nome do jogo</label><input id="season-game" name="gameName" value="${escapeHtml(season.gameName || "")}" required /></div></div><div class="form-actions"><button class="button primary" type="submit">${icon("save",16)} Salvar identidade</button></div></form></section>
      <section class="card pad"><div class="card-header"><div><h2>Ações de pontuação</h2><span class="subtle">Contadores, sim/não e seleções. Valores inválidos são bloqueados no scouting.</span></div></div><div class="tabs" role="tablist">${Object.entries(phaseInfo).map(([phase,[label]]) => `<button class="${phase === "auto" ? "active" : ""}" data-action="season-tab" data-phase="${phase}">${label}</button>`).join("")}</div>${Object.entries(phaseInfo).map(([phase,[label,description]]) => `<div class="season-panel ${phase === "auto" ? "" : "hidden"}" data-season-panel="${phase}"><div class="card inset"><div class="card-header" style="padding:12px 12px 0;margin-bottom:5px"><div><h3>${label}</h3><span class="subtle">${description}</span></div></div>${(season.actions?.[phase] || []).map(actionEditor).join("") || '<div class="empty-state"><h3>Sem ações nessa fase</h3><p>Adicione uma ação abaixo.</p></div>'}</div></div>`).join("")}<form data-form="add-season-action" class="card inset pad" style="margin-top:14px"><div class="card-header"><h3>Adicionar ação</h3></div><div class="field-grid three"><div class="field"><label>Nome</label><input name="label" placeholder="Ex.: Objeto no nível X" required maxlength="60" /></div><div class="field"><label>Fase</label><select name="phase"><option value="auto">Autonomous</option><option value="teleop" selected>TeleOp</option><option value="endgame">Endgame</option></select></div><div class="field"><label>Tipo</label><select name="inputType"><option value="counter">Contador</option><option value="boolean">Sim / não</option><option value="select">Seleção</option></select></div><div class="field"><label>Pontos</label><input type="number" name="points" min="0" max="999" value="1" required /></div><div class="field"><label>Limite</label><input type="number" name="max" min="1" max="999" value="20" required /></div><div class="field"><label>Conta ciclo?</label><select name="countsTowardCycles"><option value="false" selected>Não</option><option value="true">Sim</option></select></div></div><div class="form-actions"><button class="button" type="submit">${icon("plus",16)} Adicionar ação</button></div></form></section>
      <section class="card pad"><div class="card-header"><div><h2>Scouting Rating</h2><span class="subtle">Ajuste os pesos do ranking interno. Não substitui o ranking oficial da FTC.</span></div></div><form data-form="rating-weights"><div class="rating-breakdown">${Object.entries(RATING_WEIGHT_LABELS).map(([key,label]) => { const value = Number(weights[key] ?? 0); return `<div class="weight-row"><label for="weight-${key}">${escapeHtml(label)}</label><input id="weight-${key}" type="range" min="-20" max="50" step="1" name="${key}" value="${value}" data-action="rating-weight-input" /><output data-weight-output="${key}">${value > 0 ? "+" : ""}${value}</output></div>`; }).join("")}</div><div class="form-actions"><button class="button primary" type="submit">${icon("save",16)} Salvar pesos</button></div></form></section>
    </div>
  </section>`;
}
