import { escapeHtml, icon, sectionHeader, statusPill } from "../components/ui.js";

export function renderSettings({ state, storageInfo, online = navigator.onLine }) {
  const currentScout = (state.scouts || []).find((scout) => String(scout.id) === String(state.settings?.currentScoutId)) || state.scouts?.[0];
  const syncState = online ? "synced" : "offline";
  return `<section class="page">
    ${sectionHeader({ eyebrow: "Preferências", title: "Configurações", description: "Identidade do scout, segurança dos dados locais e exportação." })}
    <div class="admin-grid">
      <section class="card pad"><div class="card-header"><div><h2>Conta de scout</h2><span class="subtle">O autor é salvo em cada registro de scouting.</span></div>${icon("user",20)}</div><form data-form="current-scout"><div class="field"><label for="current-scout">Scout atual</label><select id="current-scout" name="scoutId">${(state.scouts || []).map((scout) => `<option value="${escapeHtml(scout.id)}" ${scout.id === currentScout?.id ? "selected" : ""}>${escapeHtml(scout.name)} · ${escapeHtml(scout.role || "Scout")}</option>`).join("")}</select></div><div class="form-actions"><button class="button primary" type="submit">${icon("save",16)} Usar esta conta</button></div></form></section>
      <section class="card pad"><div class="card-header"><div><h2>Conexão e offline</h2><span class="subtle">Rascunhos e registros ficam protegidos no navegador.</span></div>${statusPill(syncState)}</div><div class="compact-list"><div class="compact-item"><div class="item-main">${icon(online ? "sync" : "offline",18)}<div><strong>${online ? "Online · sincronizado" : "Offline · trabalhando localmente"}</strong><span>${online ? "Alterações já persistidas neste dispositivo" : "A conexão será verificada ao voltar"}</span></div></div><span class="online-dot" style="background:${online ? "var(--green)" : "var(--amber)"}"></span></div><div class="compact-item"><div class="item-main">${icon("save",18)}<div><strong>Banco local: ${escapeHtml(storageInfo?.backend || "carregando")}</strong><span>${storageInfo?.persistent ? "Persistência habilitada" : "Sessão atual em memória"}</span></div></div></div><div class="compact-item"><div class="item-main">${icon("clipboard",18)}<div><strong>${(state.syncQueue || []).length} registro(s) na fila</strong><span>O modo local não envia dados a um servidor externo.</span></div></div></div></div></section>
      <section class="card pad"><div class="card-header"><div><h2>Exportar dados</h2><span class="subtle">Baixe somente os dados existentes no banco local.</span></div>${icon("download",20)}</div><div class="export-grid"><button class="button" data-action="export-scouting-csv">${icon("download",18)}CSV de scouting</button><button class="button" data-action="export-scouting-json">${icon("download",18)}JSON completo</button><button class="button" data-action="export-teams-csv">${icon("download",18)}CSV de equipes</button><button class="button" data-action="export-state-json">${icon("download",18)}Backup JSON</button></div></section>
      <section class="card pad" style="border-color:rgba(255,114,126,.25)"><div class="card-header"><div><h2>Banco local</h2><span class="subtle">Remova equipes, partidas, registros e preferências deste navegador. Esta ação não pode ser desfeita.</span></div>${icon("alert",20)}</div><button class="button danger wide" data-action="request-reset">${icon("alert",16)} Limpar dados locais</button></section>
    </div>
  </section>`;
}

export function renderResetConfirm() {
  return `<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true"><header class="modal__header"><div><span class="eyebrow">Confirmação necessária</span><h2>Limpar dados locais?</h2><p>Todos os registros, equipes, eventos, scouts e ajustes criados neste navegador serão removidos.</p></div><button class="icon-button" data-action="close-modal" aria-label="Fechar">${icon("close")}</button></header><div class="modal__body"><div class="card inset pad"><span class="icon-text">${icon("alert",18)} Esta ação afeta apenas o banco local deste dispositivo.</span></div></div><footer class="modal__footer"><button class="button" data-action="close-modal">Cancelar</button><button class="button danger" data-action="confirm-reset">Limpar agora</button></footer></section></div>`;
}
