import { escapeHtml, icon, sectionHeader } from "../components/ui.js";
import { currentScout } from "../utils/domain.js";

export function renderSettings({ state, storageInfo, online = navigator.onLine }) {
  const scout = currentScout(state);
  const hasScouts = state.scouts.length > 0;
  return `<section class="page">
    ${sectionHeader({ eyebrow: "SEU WORKSPACE", title: "Configurações", description: "Seu perfil, seus dados e suas preferências em um só lugar." })}
    <div class="settings-grid">
      <section class="card pad"><div class="card-header"><div><h2>Seu perfil de scout</h2><span class="subtle">Cada observação é associada ao perfil escolhido.</span></div>${icon("user",20)}</div>${hasScouts ? `<form data-form="current-scout"><div class="field"><label for="current-scout">Quem está usando este dispositivo?</label><select id="current-scout" name="scoutId">${state.scouts.map((person) => `<option value="${escapeHtml(person.id)}" ${String(person.id) === String(scout?.id) ? "selected" : ""}>${escapeHtml(person.name)} · ${escapeHtml(person.role || "Scout")}</option>`).join("")}</select></div><div class="form-actions"><button class="button primary" type="submit">${icon("check",16)} Usar este perfil</button></div></form>` : `<p class="subtle">Crie seu primeiro perfil durante a preparação do evento.</p><button class="button primary" data-action="open-setup">Preparar meu evento ${icon("chevron",16)}</button>`}</section>
      <section class="card pad"><div class="card-header"><div><h2>Seus dados, sempre por perto</h2><span class="subtle">Continue observando mesmo sem internet.</span></div>${icon("save",20)}</div><div class="notice ${storageInfo?.persistent ? "success" : "warning"}">${icon(storageInfo?.persistent ? "check" : "alert",18)}<span><strong>${storageInfo?.persistent ? "Salvo neste navegador" : "Armazenamento indisponível"}</strong><br />${storageInfo?.persistent ? "Equipes, partidas e rascunhos continuam aqui depois de recarregar." : "Os dados estão apenas na sessão. Exporte um backup antes de fechar a página."}</span></div><p class="subtle">${online ? "Você está online." : "Você está offline."} Os dados ficam neste dispositivo. Para levar seus registros para outro, baixe o backup e restaure o arquivo lá.</p><span class="icon-text">${icon("clipboard",16)} ${state.scoutingRecords.length} observações · ${Object.keys(state.drafts || {}).length} rascunhos</span></section>
      <section class="card pad"><div class="card-header"><div><h2>Exportar e fazer backup</h2><span class="subtle">Planilhas para analisar. Backup para guardar tudo.</span></div>${icon("download",20)}</div><div class="export-grid"><button class="button" data-action="export-scouting-csv">${icon("chart",19)} Observações em CSV</button><button class="button" data-action="export-teams-csv">${icon("teams",19)} Equipes em CSV</button><button class="button" data-action="export-scouting-json">${icon("clipboard",19)} Observações em JSON</button><button class="button" data-action="export-state-json">${icon("save",19)} Backup completo</button></div><p class="field-hint" style="margin-top:12px">O backup completo inclui todos os eventos, equipes, registros e rascunhos.</p></section>
      <section class="card pad"><div class="card-header"><div><h2>Restaurar um backup</h2><span class="subtle">Recupere seus dados ou transfira para este dispositivo.</span></div>${icon("sync",20)}</div><p class="subtle">Selecione o arquivo JSON baixado em “Backup completo”. Vamos conferir o conteúdo antes de restaurar.</p><label class="button wide" for="backup-file">${icon("download",17)} Selecionar arquivo de backup</label><input class="sr-only" id="backup-file" type="file" accept=".json,application/json" /><p class="field-hint" style="margin-top:12px">Você verá um resumo antes de substituir os dados atuais.</p></section>
      <section class="card pad settings-danger"><div class="card-header"><div><h2>Limpar este dispositivo</h2><span class="subtle">Remove os eventos e registros salvos neste navegador.</span></div>${icon("alert",20)}</div><button class="button danger" data-action="request-reset">${icon("close",16)} Limpar dados locais</button></section>
    </div>
  </section>`;
}

export function renderResetConfirm() {
  return `<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="reset-title" tabindex="-1"><header class="modal__header"><div><span class="eyebrow">Limpar dados</span><h2 id="reset-title">Limpar este dispositivo?</h2><p>Equipes, eventos, partidas, observações e rascunhos deste navegador serão removidos. Esta ação não pode ser desfeita.</p></div><button class="icon-button" data-action="close-modal" aria-label="Fechar">${icon("close")}</button></header><div class="modal__body"><button class="button wide" data-action="export-state-json">${icon("download",17)} Baixar um backup antes de limpar</button></div><footer class="modal__footer"><button class="button" data-action="close-modal">Manter meus dados</button><button class="button danger" data-action="confirm-reset">Limpar agora</button></footer></section></div>`;
}
